 ### ARWEAVE ####
 # file: Dockerfile
version: '3.8'
services:
  arweave-node:
    container_name: arweave-node
    image: arweave-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1984:1984"
    restart: always
    environment:
      AR_RUNMODE: ${AR_RUNMODE?err} #set to <-r test> in .env for hashrate benchmarking 
                                #set to prod for normal operation <prod>
    volumes:
      - "../ardata:/mnt/arweave-data"
